Step -1- Data Understanding, Analysis and Preparations:

• To - Do - 1:

1. Read and Observe the Dataset.

In [40]:
import pandas as pd
data = pd.read_csv('/content/drive/MyDrive/Concept and technologies of AI/student.csv')

In [41]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


2. Print top(5) and bottom(5) of the dataset {Hint: pd.head and pd.tail}.

In [42]:
data.head(5)

Math  Reading  Writing
0    48       68       63
1    62       81       72
2    79       80       78
3    76       83       79
4    59       64       62

In [43]:
data.tail(5)

Math  Reading  Writing
995    72       74       70
996    73       86       90
997    89       87       94
998    83       82       78
999    66       66       72

3. Print the Information of Datasets. {Hint: pd.info}.

In [44]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Math     1000 non-null   int64
 1   Reading  1000 non-null   int64
 2   Writing  1000 non-null   int64
dtypes: int64(3)
memory usage: 23.6 KB


4. Gather the Descriptive info about the Dataset. {Hint: pd.describe}

In [45]:
data.describe()

Math      Reading      Writing
count  1000.000000  1000.000000  1000.000000
mean     67.290000    69.872000    68.616000
std      15.085008    14.657027    15.241287
min      13.000000    19.000000    14.000000
25%      58.000000    60.750000    58.000000
50%      68.000000    70.000000    69.500000
75%      78.000000    81.000000    79.000000
max     100.000000   100.000000   100.000000

5. Split your data into Feature (X) and Label (Y).

In [46]:
X = data[['Math', 'Reading']]
Y = data['Writing']

To - Do - 2:
1. To make the task easier - let’s assume there is no bias or intercept.
2. Create the following matrices:

In [47]:
import numpy as np

In [48]:
data = pd.read_csv('/content/drive/MyDrive/Concept and technologies of AI/student.csv')
X = data[['Math', 'Reading']].values
Y = data['Writing'].values

# Step 2: Initialize W (weight vector) randomly
W = np.random.randn(X.shape[1], 1)

# Step 3: Convert X into the required matrix form
X = X.T

# Step 4: Convert Y into the required matrix form (shape (n, 1))
Y = Y.reshape(-1, 1)  # Convert Y to shape (n, 1)

# Display the matrices
print("Matrix X (Feature matrix):")
print(X)

print("\nMatrix W (Weight vector):")
print(W)

print("\nMatrix Y (Target vector):")
print(Y)

Matrix X (Feature matrix):
[[48 62 79 ... 89 83 66]
 [68 81 80 ... 87 82 66]]

Matrix W (Weight vector):
[[-1.95827161]
 [-0.51796269]]

Matrix Y (Target vector):
[[ 63]
 [ 72]
 [ 78]
 [ 79]
 [ 62]
 [ 85]
 [ 83]
 [ 41]
 [ 80]
 [ 77]
 [ 64]
 [ 90]
 [ 45]
 [ 77]
 [ 70]
 [ 46]
 [ 76]
 [ 44]
 [ 85]
 [ 72]
 [ 53]
 [ 66]
 [ 75]
 [ 49]
 [ 84]
 [ 83]
 [ 68]
 [ 66]
 [ 77]
 [ 78]
 [ 74]
 [ 83]
 [ 72]
 [ 65]
 [ 46]
 [ 66]
 [ 50]
 [ 79]
 [ 68]
 [ 46]
 [ 86]
 [ 70]
 [ 61]
 [ 53]
 [ 72]
 [ 75]
 [ 50]
 [ 77]
 [100]
 [ 81]
 [100]
 [ 87]
 [ 78]
 [ 48]
 [ 50]
 [ 44]
 [ 48]
 [ 43]
 [ 67]
 [ 78]
 [ 58]
 [ 91]
 [ 92]
 [ 78]
 [ 42]
 [ 85]
 [ 73]
 [ 83]
 [ 61]
 [ 58]
 [ 60]
 [ 55]
 [ 48]
 [ 62]
 [ 68]
 [ 59]
 [ 62]
 [ 48]
 [ 74]
 [ 63]
 [ 80]
 [ 79]
 [ 73]
 [ 79]
 [ 45]
 [ 67]
 [ 89]
 [ 77]
 [ 81]
 [ 88]
 [ 53]
 [ 68]
 [ 79]
 [ 77]
 [ 63]
 [ 73]
 [ 60]
 [ 67]
 [100]
 [ 79]
 [ 26]
 [ 51]
 [ 80]
 [ 57]
 [ 41]
 [ 78]
 [ 68]
 [ 49]
 [ 76]
 [ 41]
 [ 71]
 [ 77]
 [ 89]
 [ 86]
 [ 55]
 [ 80]
 [ 56]
 [ 74]
 [ 85]
 [ 8

To - Do - 3:
1. Split the dataset into training and test sets.
2. You can use an 80-20 or 70-30 split, with 80% (or 70%) of the data used for training and the rest
for testing.

In [49]:
from sklearn.model_selection import train_test_split

# Load the dataset
data = pd.read_csv('/content/drive/MyDrive/Concept and technologies of AI/student.csv')

# Step 1: Split the data into features (X) and label (Y)
X = data[['Math', 'Reading']].values
Y = data['Writing'].values

# Step 2: Split the data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# Step 3: Reshape the target vectors into column vectors (for consistency)
Y_train = Y_train.reshape(-1, 1)
Y_test = Y_test.reshape(-1, 1)

# Step 4: Print the shape of the resulting datasets to verify the split
print("Training set (X_train) shape:", X_train.shape)
print("Test set (X_test) shape:", X_test.shape)
print("Training labels (Y_train) shape:", Y_train.shape)
print("Test labels (Y_test) shape:", Y_test.shape)


Training set (X_train) shape: (800, 2)
Test set (X_test) shape: (200, 2)
Training labels (Y_train) shape: (800, 1)
Test labels (Y_test) shape: (200, 1)


In [50]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

# Step 1: Load the data and split it into training and test sets
data = pd.read_csv('/content/drive/MyDrive/Concept and technologies of AI/student.csv')
X = data[['Math', 'Reading']].values  # Feature matrix
Y = data['Writing'].values.reshape(-1, 1)  # Target vector (reshaped into a column vector)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# Step 2: Prepare the feature matrix (X) and target vector (Y)
X_train = X_train / np.max(X_train, axis=0)
X_test = X_test / np.max(X_test, axis=0)

# Step 3: Define the weight matrix (W) and initialize learning rate and number of iterations
W = np.random.randn(X_train.shape[1], 1)
alpha = 0.01
iterations = 1000

# Gradient Descent Function
def gradient_descent(X, Y, W, alpha, iterations):
    m = len(Y)
    for i in range(iterations):
        # Calculate predictions
        Y_pred = np.dot(X, W)
        # Compute loss
        loss = Y_pred - Y
        # Compute gradient
        dW = (1 / m) * np.dot(X.T, loss)
        # Update weights
        W = W - alpha * dW
        # Optional: Print loss every 100 iterations
        if i % 100 == 0:
            print(f"Iteration {i}, Loss: {np.mean(loss**2)}")

    return W

# Step 4: Call the gradient descent function to learn the parameters
W_optimized = gradient_descent(X_train, Y_train, W, alpha, iterations)

# Step 5: Evaluate the model using RMSE and R^2
Y_test_pred = np.dot(X_test, W_optimized)

# Compute RMSE
rmse = np.sqrt(mean_squared_error(Y_test, Y_test_pred))

# Compute R^2 Score
r2 = r2_score(Y_test, Y_test_pred)

print("Root Mean Squared Error (RMSE):", rmse)
print("R-squared (R2):", r2)

Iteration 0, Loss: 5024.0129099303795
Iteration 100, Loss: 727.5779618747752
Iteration 200, Loss: 130.83410323876143
Iteration 300, Loss: 47.86127605443866
Iteration 400, Loss: 36.23589446107741
Iteration 500, Loss: 34.519301272678234
Iteration 600, Loss: 34.17960171667618
Iteration 700, Loss: 34.031977819819296
Iteration 800, Loss: 33.9118883742962
Iteration 900, Loss: 33.79647642440609
Root Mean Squared Error (RMSE): 5.906620021372308
R-squared (R2): 0.8606245894645321


To-Do:
 1. Loads the data and splits it into training and test sets.

In [51]:
data = pd.read_csv('/content/drive/MyDrive/Concept and technologies of AI/student.csv')
print(data.head())

   Math  Reading  Writing
0    48       68       63
1    62       81       72
2    79       80       78
3    76       83       79
4    59       64       62


 2. Prepares the feature matrix(X) and target vector(Y).

In [52]:
X = data[['Math', 'Reading']].values  # Feature matrix
Y = data['Writing'].values.reshape(-1, 1)

# Step 2: Optionally, normalize or scale the features for better gradient descent performance
X = X / np.max(X, axis=0)

# Step 3: Print shapes to verify
print("Feature matrix (X) shape:", X.shape)
print("Target vector (Y) shape:", Y.shape)

# Step 4: Optional: Display a few rows of the prepared feature matrix and target vector
print("Sample features (X):", X[:5])
print("Sample target (Y):", Y[:5])

Feature matrix (X) shape: (1000, 2)
Target vector (Y) shape: (1000, 1)
Sample features (X): [[0.48 0.68]
 [0.62 0.81]
 [0.79 0.8 ]
 [0.76 0.83]
 [0.59 0.64]]
Sample target (Y): [[63]
 [72]
 [78]
 [79]
 [62]]


Defines the weight matrix(W)and initializes the learning rate and number of iterations.

In [53]:
# Step 1: Define the weight matrix (W)
W = np.random.randn(2, 1)  # For 2 features: 'Math' and 'Reading'

# Step 2: Initialize the learning rate (alpha)
alpha = 0.01  # Small positive value to control the step size during updates

# Step 3: Set the number of iterations
iterations = 1000

# Display the initialized parameters
print("Initial weight matrix (W):", W)
print("Learning rate (alpha):", alpha)
print("Number of iterations:", iterations)

Initial weight matrix (W): [[-0.71952667]
 [-0.11861612]]
Learning rate (alpha): 0.01
Number of iterations: 1000


# 5. Evaluates the model using RMSE and R2

In [54]:
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

# Step 1: Predict values for the test set
Y_test_pred = np.dot(X_test, W_optimized)

# Step 2: Compute RMSE
rmse = np.sqrt(mean_squared_error(Y_test, Y_test_pred))

# Step 3: Compute R²
r2 = r2_score(Y_test, Y_test_pred)

# Step 4: Print the evaluation metrics
print("Root Mean Squared Error (RMSE):", rmse)
print("R-squared (R²):", r2)


Root Mean Squared Error (RMSE): 5.906620021372308
R-squared (R²): 0.8606245894645321


Present your finding:
 1. Did your Model Overfitt, Underfitts, or performance is acceptable.
 2. Experiment with different value of learning rate, making it higher and lower, observe the result.

In [55]:
learning_rates = [0.001, 0.01, 0.1, 0.5]

for lr in learning_rates:
    print(f"\nExperimenting with learning rate: {lr}")
    W = np.random.randn(X_train.shape[1], 1)
    W_optimized = gradient_descent(X_train, Y_train, W, alpha=lr, iterations=1000)

    # Predict and evaluate
    Y_test_pred = np.dot(X_test, W_optimized)
    rmse = np.sqrt(mean_squared_error(Y_test, Y_test_pred))
    r2 = r2_score(Y_test, Y_test_pred)

    print(f"Learning Rate: {lr}")
    print(f"RMSE: {rmse}")
    print(f"R-squared (R^2): {r2}")



Experimenting with learning rate: 0.001
Iteration 0, Loss: 5094.265396737515
Iteration 100, Loss: 4191.337015747409
Iteration 200, Loss: 3449.523538679681
Iteration 300, Loss: 2840.0759007502147
Iteration 400, Loss: 2339.374970887871
Iteration 500, Loss: 1928.0161751785856
Iteration 600, Loss: 1590.0574585290292
Iteration 700, Loss: 1312.4014387585987
Iteration 800, Loss: 1084.2878080534801
Iteration 900, Loss: 896.8763094329194
Learning Rate: 0.001
RMSE: 27.310844607304436
R-squared (R^2): -1.9797398954063197

Experimenting with learning rate: 0.01
Iteration 0, Loss: 5037.402092874841
Iteration 100, Loss: 728.8083811396095
Iteration 200, Loss: 130.38144663153568
Iteration 300, Loss: 47.18023921039266
Iteration 400, Loss: 35.528442783674016
Iteration 500, Loss: 33.81343593224549
Iteration 600, Loss: 33.47916614074408
Iteration 700, Loss: 33.3374610753885
Iteration 800, Loss: 33.22331409665739
Iteration 900, Loss: 33.113803994741005
Learning Rate: 0.01
RMSE: 5.851328784625326
R-squared

Observations:
1. Very Low Learning Rate


*   Model converges very slowly.
*   Loss decreases at a sluggish pace, requiring more iterations for acceptable performance.

2. Optimal Learning Rate

*   Achieves convergence in a reasonable number of iterations.
*   Produces good RMSE and 𝑅2 scores.

3. High learning rate


*   Loss might oscillate or even diverge.
*   RMSE increases, and 𝑅2 may decrease due to instability.


Build a Cost Function:

In [56]:
#Define the cost function
def cost_function(X, Y, W):
    """ Parameters:
    This function finds the Mean Square Error.
    Input parameters:
    X: Feature Matrix
    Y: Target Matrix
    W: Weight Matrix
    Output Parameters:
    cost: accumulated mean square error.
    """
    # Calculate predictions
    Y_pred = np.dot(X, W)

    # Calculate the difference between predictions and actual values
    error = Y_pred - Y

    # Calculate the squared error
    squared_error = error**2

    # Calculate the mean squared error
    cost = np.mean(squared_error)

    return cost # Return the calculated cost

Designing a Test Case for Cost Function:

In [57]:
X_test = np.array([[1, 2], [3, 4], [5, 6]])
Y_test = np.array([3, 7, 11])
W_test = np.array([1, 1])
cost = cost_function(X_test, Y_test, W_test)
if cost == 0:
    X_test = np.array([[1, 2], [3, 4], [5, 6]])
    Y_test = np.array([3, 7, 11])
    W_test = np.array([1, 1])
    cost = cost_function(X_test, Y_test, W_test)
    if cost == 0:
        print("Proceed Further")
else:
    print("something went wrong: Reimplement")

Proceed Further


Gradient Descent Update Rule

In [58]:
def gradient_descent(X, Y, W, alpha, iterations):
    """
    Perform gradient descent to optimize the parameters of a linear regression model.
    Parameters:
    X (numpy.ndarray): Feature matrix (m x n).
    Y (numpy.ndarray): Target vector (m x 1).
    W (numpy.ndarray): Initial guess for parameters (n x 1).
    alpha (float): Learning rate.
    iterations (int): Number of iterations for gradient descent.
    Returns:
    tuple: A tuple containing the final optimized parameters (W_update) and the history of cost values
    .
    W_update (numpy.ndarray): Updated parameters (n x 1).
    cost_history (list): History of cost values over iterations.
    """
    # Initialize cost history
    cost_history = [0] * iterations
    # Number of samples
    m = len(Y)
    for iteration in range(iterations):
        # Step 1: Hypothesis Values
        Y_pred = np.dot(X, W)  # Prediction using current weights
        # Step 2: Difference between Hypothesis and Actual Y
        loss = Y_pred - Y     # Error calculation
        # Step 3: Gradient Calculation
        dw = (1/m) * np.dot(X.T, loss)  # Gradient of the cost function
        # Step 4: Updating Values of W using Gradient
        W_update = W - alpha * dw    # Weight update using gradient descent
        # Step 5: New Cost Value
        cost = cost_function(X, Y, W_update)
        cost_history[iteration] = cost
    return W_update, cost_history # Return updated weights and cost history



Test Code for Gradient Descent function:

In [59]:
# Generate random test data
np.random.seed(0) # For reproducibility
X = np.random.rand(100, 3) # 100 samples, 3 features
Y = np.random.rand(100)
W = np.random.rand(3) # Initial guess for parameters
# Set hyperparameters
alpha = 0.01
iterations = 1000
# Test the gradient_descent function
final_params, cost_history = gradient_descent(X, Y, W, alpha, iterations)
# Print the final parameters and cost history
print("Final Parameters:", final_params)
print("Cost History:", cost_history)

Final Parameters: [0.3996496  0.92745322 0.09826523]
Cost History: [0.21422394189320307, 0.21422394189320307, 0.21422394189320307, 0.21422394189320307, 0.21422394189320307, 0.21422394189320307, 0.21422394189320307, 0.21422394189320307, 0.21422394189320307, 0.21422394189320307, 0.21422394189320307, 0.21422394189320307, 0.21422394189320307, 0.21422394189320307, 0.21422394189320307, 0.21422394189320307, 0.21422394189320307, 0.21422394189320307, 0.21422394189320307, 0.21422394189320307, 0.21422394189320307, 0.21422394189320307, 0.21422394189320307, 0.21422394189320307, 0.21422394189320307, 0.21422394189320307, 0.21422394189320307, 0.21422394189320307, 0.21422394189320307, 0.21422394189320307, 0.21422394189320307, 0.21422394189320307, 0.21422394189320307, 0.21422394189320307, 0.21422394189320307, 0.21422394189320307, 0.21422394189320307, 0.21422394189320307, 0.21422394189320307, 0.21422394189320307, 0.21422394189320307, 0.21422394189320307, 0.21422394189320307, 0.21422394189320307, 0.214223

Root Mean Square Error:

In [60]:
# Model Evaluation - RMSE
def rmse(Y, Y_pred):
    """
    This Function calculates the Root Mean Squres.
    Input Arguments:
    Y: Array of actual(Target) Dependent Varaibles.
    Y_pred: Array of predeicted Dependent Varaibles.
    Output Arguments:
    rmse: Root Mean Square.
    """
    rmse = np.sqrt(np.mean((Y - Y_pred)**2)) # Calculate RMSE
    return rmse # Return the calculated RMSE

Code for R-Squared Error:

In [61]:
# Model Evaluation - R2
def r2(Y, Y_pred):
    """
    This Function calculates the R Squared Error.
    Input Arguments:
    Y: Array of actual(Target) Dependent Varaibles.
    Y_pred: Array of predeicted Dependent Varaibles.
    Output Arguments:
    rsquared: R Squared Error.
    """
    mean_y = np.mean(Y)
    ss_tot = np.sum((Y - mean_y)**2) # Calculate total sum of squares
    ss_res = np.sum((Y - Y_pred)**2) # Calculate residual sum of squares
    r2 = 1 - (ss_res / ss_tot)     # Calculate R-squared
    return r2 # Return the calculated R-squared

Main Function to Integrate All Steps:

In [62]:
def main():
    # Step 1: Load the dataset
    data = pd.read_csv('/content/drive/MyDrive/Concept and technologies of AI/student.csv')
    # Step 2: Split the data into features (X) and target (Y)
    X = data[['Math', 'Reading']].values # Features: Math and Reading marks
    Y = data['Writing'].values # Target: Writing marks
    # Step 3: Split the data into training and test sets (80% train, 20% test)
    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
    # Step 4: Initialize weights (W) to zeros, learning rate and number of iterations
    W = np.zeros(X_train.shape[1]) # Initialize weights
    alpha = 0.00001 # Learning rate
    iterations = 1000 # Number of iterations for gradient descent
    # Step 5: Perform Gradient Descent
    W_optimal, cost_history = gradient_descent(X_train, Y_train, W, alpha, iterations)
    # Step 6: Make predictions on the test set
    Y_pred = np.dot(X_test, W_optimal)
    # Step 7: Evaluate the model using RMSE and R-Squared
    model_rmse = rmse(Y_test, Y_pred)
    model_r2 = r2(Y_test, Y_pred)
    # Step 8: Output the results
    print("Final Weights:", W_optimal)
    print("Cost History (First 10 iterations):", cost_history[:10])
    print("RMSE on Test Set:", model_rmse)
    print("R-Squared on Test Set:", model_r2)
# Execute the main function
if __name__ == "__main__":
    main()

Final Weights: [0.04797833 0.05020199]
Cost History (First 10 iterations): [4026.33114156751, 4026.33114156751, 4026.33114156751, 4026.33114156751, 4026.33114156751, 4026.33114156751, 4026.33114156751, 4026.33114156751, 4026.33114156751, 4026.33114156751]
RMSE on Test Set: 63.36563528655014
R-Squared on Test Set: -15.04041794561271
